spring:
  config:
    activate:
      on-profile: default
  application:
    name: SB Dockerfile test
server:
  port: 8080
db:
  url: "jdbc:postgresql://localhost:5432/test"
  name: "beavers"
---

spring:
  config:
    activate:
      on-profile: cloud
server:
  port: ${APP_PORT}
db:
  url: ${DB_URL}
  name: ${DB_NAME}
